# Lines configured by zsh-newuser-install
HISTFILE=~/.zshhistory
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/lambda/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Our fancy pretty prompt setup
PROMPT='%F{green}%n%f@%F{red}%m%f %F{blue}%B%~%b%f %# '
RPROMPT='[%F{yellow}%?%f]'

# Force some aliases
alias ls='ls --color=auto'

# Sane editing keybinds
bindkey "\e[3~" delete-char 
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^[Od" backward-word
bindkey "^[Oc" forward-word
bindkey "^H" backward-kill-word
bindkey  "^[[3^" kill-word

which gpg > /dev/null

if [ $? -eq 0 ]; then
    # Enable gpg-agent if it is not running
    export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
    gpgconf --launch gpg-agent

    gpg-connect-agent updatestartuptty /bye > /dev/null
fi

# Editor exports
which emacs > /dev/null

if [ $? -eq 0 ]; then
    export EDITOR=$(which emacs)
fi