# Lines configured by zsh-newuser-install
HISTFILE=~/.zshhistory
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/lambda/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Our fancy pretty prompt setup.
PROMPT='%F{green}%n%f@%F{red}%m%f %F{blue}%B%~%b%f %# '
RPROMPT='[%F{yellow}%?%f]'

# Enable gpg-agent if it is not running
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

gpg-connect-agent updatestartuptty /bye > /dev/null

# Force some aliases.
alias ls='ls --color=auto'

# Editor exports
which emacs > /dev/null

if [ $? -eq 0 ]; then
    export EDITOR=$(which emacs)
fi